#include "unlimited/protocol.hpp"

namespace unlimited {

// Generated by tools/gen_tables.cpp: round(65534 * sin(pi/2 * i/256)).
const uint16_t k_quarter_sine[k_quarter_table_size] UNLIMITED_ROM = {
    0, 402, 804, 1206, 1608, 2010, 2412, 2814, 3216, 3617, 4019, 4420,
    4821, 5222, 5623, 6023, 6423, 6824, 7223, 7623, 8022, 8421, 8820, 9218,
    9616, 10013, 10411, 10807, 11204, 11600, 11995, 12390, 12785, 13179, 13573, 13966,
    14359, 14751, 15142, 15533, 15923, 16313, 16702, 17091, 17479, 17866, 18253, 18638,
    19024, 19408, 19792, 20175, 20557, 20938, 21319, 21699, 22078, 22456, 22833, 23210,
    23585, 23960, 24334, 24707, 25079, 25450, 25820, 26189, 26557, 26924, 27290, 27655,
    28019, 28382, 28744, 29105, 29465, 29823, 30181, 30537, 30893, 31247, 31599, 31951,
    32302, 32651, 32999, 33346, 33691, 34035, 34378, 34720, 35061, 35400, 35737, 36074,
    36409, 36742, 37075, 37406, 37735, 38063, 38390, 38715, 39039, 39361, 39682, 40001,
    40319, 40635, 40950, 41263, 41574, 41884, 42193, 42500, 42805, 43109, 43411, 43711,
    44010, 44307, 44603, 44896, 45188, 45479, 45767, 46054, 46340, 46623, 46905, 47185,
    47463, 47739, 48014, 48287, 48557, 48827, 49094, 49359, 49623, 49885, 50144, 50402,
    50658, 50913, 51165, 51415, 51663, 51910, 52154, 52397, 52637, 52876, 53113, 53347,
    53580, 53810, 54039, 54265, 54490, 54712, 54932, 55150, 55367, 55581, 55793, 56003,
    56210, 56416, 56620, 56821, 57020, 57217, 57412, 57605, 57796, 57984, 58171, 58355,
    58537, 58716, 58894, 59069, 59242, 59413, 59581, 59748, 59912, 60074, 60233, 60391,
    60546, 60698, 60849, 60997, 61143, 61286, 61428, 61567, 61703, 61837, 61969, 62099,
    62226, 62351, 62474, 62594, 62712, 62828, 62941, 63052, 63160, 63266, 63370, 63471,
    63570, 63667, 63761, 63852, 63942, 64029, 64113, 64195, 64275, 64352, 64427, 64499,
    64569, 64637, 64702, 64764, 64825, 64882, 64938, 64991, 65041, 65089, 65135, 65178,
    65218, 65257, 65292, 65326, 65356, 65385, 65411, 65434, 65455, 65474, 65490, 65503,
    65514, 65523, 65529, 65533, 65534
};

namespace {

const uint32_t k_half_turn = 0x80000000u;
const uint32_t k_quarter_turn = 0x40000000u;
const uint32_t k_quarter_mask = k_quarter_turn - 1u;
// A quarter is 30 bits of phase; shifted up by 2 its table index is the top byte and the fraction the 16 bits below:
// byte moves only on AVR, where a shift by any other count is a loop over 4 bytes.
const uint8_t k_position_shift = 32 - 30;
const uint8_t k_index_shift = 32 - k_quarter_table_bits;
const uint8_t k_fraction_shift = k_index_shift - 16;
const uint8_t k_word_shift = 16;
const uint32_t k_word_round = static_cast<uint32_t>(1) << k_word_shift;  // half a unit of the value's 17th bit
const int16_t k_q15_top = 32767;

}  // namespace

// Linear interpolation between table points, h = pi/512: it sags below the sine by at most h^2/8 = 0.15 LSB, the
// table rounds to 0.25 LSB and the output to 0.5 LSB, so the error stays within 1 LSB (test U1). One 16 x 16 multiply,
// no 32 x 32 one (the AVR encoder calls this at most twice per sample in an 8 kHz ISR).
int16_t sine_q15(uint32_t phase) {
    const bool negative = (phase & k_half_turn) != 0;
    uint32_t x = phase & k_quarter_mask;
    if ((phase & k_quarter_turn) != 0) {
        if (x == 0) return negative ? static_cast<int16_t>(-k_q15_top) : k_q15_top;
        x = k_quarter_turn - x;
    }
    const uint32_t position = x << k_position_shift;
    const uint8_t index = static_cast<uint8_t>(position >> k_index_shift);
    const uint16_t t = static_cast<uint16_t>(position >> k_fraction_shift);
    const uint16_t low = rom_read_u16(&k_quarter_sine[index]);
    const uint16_t step = static_cast<uint16_t>(rom_read_u16(&k_quarter_sine[index + 1]) - low);
    // In units of 1/65534, times 2^16: low + step <= 65534 keeps it below 2^32. Q15 is one bit less, rounded.
    const uint32_t value = (static_cast<uint32_t>(low) << k_word_shift) + static_cast<uint32_t>(step) * t;
    const uint16_t word = static_cast<uint16_t>((value + k_word_round) >> k_word_shift);
    const int16_t magnitude = static_cast<int16_t>(word >> 1);
    return negative ? static_cast<int16_t>(-magnitude) : magnitude;
}

int16_t cosine_q15(uint32_t phase) {
    return sine_q15(phase + k_quarter_turn);
}

// Mode header and data mapping (spec 1.5, 2.2).

namespace {

const uint16_t k_us_per_ms = 1000;
const uint8_t k_field_bits = 3;  // a, b and c are GF(8) elements
const uint8_t k_field_mask = (1u << k_field_bits) - 1u;
const uint8_t k_b_shift = k_field_bits;
const uint8_t k_c_shift = 2 * k_field_bits;
const uint8_t k_spacing_bit = 0x01;  // bit 0 of c (word bit 6)
const uint8_t k_n_code_shift = 1;    // bits 1..2 of c (word bits 7..8)
const uint8_t k_n_code_reserved = 3;

// GF(8) = GF(2)[x] / (x^3 + x + 1); alpha = x = 2.
const uint8_t k_gf8_overflow = 0x08;
const uint8_t k_gf8_reduce = 0x0B;
const uint8_t k_gf8_alpha = 2;
const uint8_t k_gray_shifts = 3;  // v ^= v >> 1, 2, 4 undoes the Gray code of a byte
const uint8_t k_rotation_divisor_bits = 3;  // r = (M / 8) | 1

uint8_t gf8_mul(uint8_t a, uint8_t b) {
    uint8_t product = 0;
    for (uint8_t bit = 0; bit < k_field_bits; ++bit) {
        if ((b & (1u << bit)) != 0) product ^= a;
        a = static_cast<uint8_t>(a << 1);
        if ((a & k_gf8_overflow) != 0) a ^= k_gf8_reduce;
    }
    return product;
}

// x_0 = 0, then x_j = alpha^(j - 1): {0, 1, 2, 4, 3, 6, 7, 5}, the slot order that keeps misaligned windows
// >= 3 of 7 symbols from every codeword.
uint8_t slot_element(uint8_t slot) {
    if (slot == 0) return 0;
    uint8_t x = 1;
    for (uint8_t j = 1; j < slot; ++j) x = gf8_mul(x, k_gf8_alpha);
    return x;
}

uint8_t tone_mask(uint8_t bits_per_peak) {
    return static_cast<uint8_t>((1u << bits_per_peak) - 1u);
}

}  // namespace

uint16_t header_word(uint8_t bits_per_peak, uint8_t data_slots, uint32_t slot_us, Spacing spacing) {
    uint8_t n_code = k_n_code_reserved;
    for (uint8_t code = 0; code < k_n_code_reserved; ++code)
        if (data_slots == (k_min_data_slots << code)) n_code = code;
    const uint8_t a = static_cast<uint8_t>((bits_per_peak - 1u) & k_field_mask);
    const uint8_t b = static_cast<uint8_t>((slot_us / k_us_per_ms) % k_header_slot_ms_modulo);
    const uint8_t spacing_bit = spacing == Spacing::dense ? k_spacing_bit : 0;
    const uint8_t c = static_cast<uint8_t>((n_code << k_n_code_shift) | spacing_bit);
    return static_cast<uint16_t>(a | (b << k_b_shift) | (c << k_c_shift));
}

HeaderFields header_fields(uint16_t word) {
    const uint8_t c = static_cast<uint8_t>((word >> k_c_shift) & k_field_mask);
    const uint8_t n_code = static_cast<uint8_t>(c >> k_n_code_shift);
    HeaderFields fields;
    fields.bits_per_peak = static_cast<uint8_t>((word & k_field_mask) + 1u);
    fields.data_slots = n_code == k_n_code_reserved ? 0 : static_cast<uint8_t>(k_min_data_slots << n_code);
    fields.slot_ms_residue = static_cast<uint8_t>((word >> k_b_shift) & k_field_mask);
    fields.spacing = (c & k_spacing_bit) != 0 ? Spacing::dense : Spacing::standard;
    return fields;
}

// h_j = x_j^3 + c x_j^2 + b x_j + a over GF(8): RS(8,3) plus the x^3 coset (d_min 6, a tone at most 3 times).
uint8_t header_symbol(uint16_t word, uint8_t slot) {
    const uint8_t a = static_cast<uint8_t>(word & k_field_mask);
    const uint8_t b = static_cast<uint8_t>((word >> k_b_shift) & k_field_mask);
    const uint8_t c = static_cast<uint8_t>((word >> k_c_shift) & k_field_mask);
    const uint8_t x = slot_element(static_cast<uint8_t>(slot & k_field_mask));
    const uint8_t x2 = gf8_mul(x, x);
    return static_cast<uint8_t>(gf8_mul(x2, x) ^ gf8_mul(c, x2) ^ gf8_mul(b, x) ^ a);
}

uint8_t gray_encode(uint8_t value) {
    return static_cast<uint8_t>(value ^ (value >> 1));
}

uint8_t gray_decode(uint8_t value) {
    for (uint8_t i = 0; i < k_gray_shifts; ++i) value = static_cast<uint8_t>(value ^ (value >> (1u << i)));
    return value;
}

uint8_t tone_rotation(uint8_t bits_per_peak) {
    return static_cast<uint8_t>(((1u << bits_per_peak) >> k_rotation_divisor_bits) | 1u);
}

// Tone n of the de-rotated grid carries the label gray(n): neighbouring tones (cyclically) differ in one bit, so a
// peak read one tone off costs one bit (D33).
uint8_t peak_tone(uint8_t symbol, uint8_t slot, uint8_t bits_per_peak) {
    const unsigned shift = static_cast<unsigned>(slot) * tone_rotation(bits_per_peak);
    return static_cast<uint8_t>((gray_decode(symbol) + shift) & tone_mask(bits_per_peak));
}

uint8_t peak_symbol(uint8_t tone, uint8_t slot, uint8_t bits_per_peak) {
    const unsigned shift = static_cast<unsigned>(slot) * tone_rotation(bits_per_peak);
    return gray_encode(static_cast<uint8_t>((tone - shift) & tone_mask(bits_per_peak)));
}

}  // namespace unlimited
